# Generated by Django 3.2.6 on 2021-08-23 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rooms_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='rndid',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, null=True),
        ),
    ]
