# Generated by Django 3.2.6 on 2021-09-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_rooms_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='rooms',
            field=models.CharField(max_length=255),
        ),
    ]
